# -----------------------------
# Builder Stage
# -----------------------------
FROM golang:1.25 AS builder

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64

RUN mkdir /common
COPY services/common /common

WORKDIR /app

COPY services/telegram_bot/go.mod services/telegram_bot/go.sum ./
RUN go mod download

COPY services/telegram_bot .

RUN go build -ldflags="-s -w" -o telegram_bot main.go

# -----------------------------
# Final Stage
# -----------------------------
FROM debian:trixie-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder --chmod=755 /app/telegram_bot /usr/local/bin/telegram_bot
COPY --chmod=755 services/telegram_bot/scripts/docker_start.sh /docker_start.sh

VOLUME ["/opt/ocserv_dashboard/uploads/receipts"]

CMD ["/docker_start.sh"]
