/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CustomerCiscoSetupResponse } from '../models';
// @ts-ignore
import type { CustomerSummaryData } from '../models';
// @ts-ignore
import type { CustomerSummaryResponse } from '../models';
// @ts-ignore
import type { MiddlewaresTooManyRequests } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * CustomersApi - axios parameter creator
 * @export
 */
export const CustomersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Download customer\'s own .p12 certificate bundle using ocserv username/password
         * @summary Download customer certificate
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersCertificatePost: async (request: CustomerSummaryData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('customersCertificatePost', 'request', request)
            const localVarPath = `/customers/certificate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * disconnects all online sessions for a customer
         * @summary Disconnect all online sessions of a customer
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersDisconnectSessionsPost: async (request: CustomerSummaryData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('customersDisconnectSessionsPost', 'request', request)
            const localVarPath = `/customers/disconnect_sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Download customer\'s PKCS#12 certificate using a short-lived Cisco Secure Client setup token
         * @summary Download customer Cisco Secure Client setup certificate
         * @param {string} token Cisco Secure Client setup certificate token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSetupCiscoCertificateTokenGet: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('customersSetupCiscoCertificateTokenGet', 'token', token)
            const localVarPath = `/customers/setup/cisco/certificate/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create Cisco Secure Client certificate import and connection creation URIs using ocserv username/password
         * @summary Create customer Cisco Secure Client setup links
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSetupCiscoPost: async (request: CustomerSummaryData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('customersSetupCiscoPost', 'request', request)
            const localVarPath = `/customers/setup/cisco`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Customer summary account
         * @summary Customer summary account
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSummaryPost: async (request: CustomerSummaryData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('customersSummaryPost', 'request', request)
            const localVarPath = `/customers/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustomersApi - functional programming interface
 * @export
 */
export const CustomersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomersApiAxiosParamCreator(configuration)
    return {
        /**
         * Download customer\'s own .p12 certificate bundle using ocserv username/password
         * @summary Download customer certificate
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customersCertificatePost(request: CustomerSummaryData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.customersCertificatePost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomersApi.customersCertificatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * disconnects all online sessions for a customer
         * @summary Disconnect all online sessions of a customer
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customersDisconnectSessionsPost(request: CustomerSummaryData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.customersDisconnectSessionsPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomersApi.customersDisconnectSessionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Download customer\'s PKCS#12 certificate using a short-lived Cisco Secure Client setup token
         * @summary Download customer Cisco Secure Client setup certificate
         * @param {string} token Cisco Secure Client setup certificate token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customersSetupCiscoCertificateTokenGet(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.customersSetupCiscoCertificateTokenGet(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomersApi.customersSetupCiscoCertificateTokenGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create Cisco Secure Client certificate import and connection creation URIs using ocserv username/password
         * @summary Create customer Cisco Secure Client setup links
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customersSetupCiscoPost(request: CustomerSummaryData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerCiscoSetupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.customersSetupCiscoPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomersApi.customersSetupCiscoPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Customer summary account
         * @summary Customer summary account
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customersSummaryPost(request: CustomerSummaryData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.customersSummaryPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomersApi.customersSummaryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CustomersApi - factory interface
 * @export
 */
export const CustomersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomersApiFp(configuration)
    return {
        /**
         * Download customer\'s own .p12 certificate bundle using ocserv username/password
         * @summary Download customer certificate
         * @param {CustomersApiCustomersCertificatePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersCertificatePost(requestParameters: CustomersApiCustomersCertificatePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.customersCertificatePost(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * disconnects all online sessions for a customer
         * @summary Disconnect all online sessions of a customer
         * @param {CustomersApiCustomersDisconnectSessionsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersDisconnectSessionsPost(requestParameters: CustomersApiCustomersDisconnectSessionsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.customersDisconnectSessionsPost(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * Download customer\'s PKCS#12 certificate using a short-lived Cisco Secure Client setup token
         * @summary Download customer Cisco Secure Client setup certificate
         * @param {CustomersApiCustomersSetupCiscoCertificateTokenGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSetupCiscoCertificateTokenGet(requestParameters: CustomersApiCustomersSetupCiscoCertificateTokenGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.customersSetupCiscoCertificateTokenGet(requestParameters.token, options).then((request) => request(axios, basePath));
        },
        /**
         * Create Cisco Secure Client certificate import and connection creation URIs using ocserv username/password
         * @summary Create customer Cisco Secure Client setup links
         * @param {CustomersApiCustomersSetupCiscoPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSetupCiscoPost(requestParameters: CustomersApiCustomersSetupCiscoPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerCiscoSetupResponse> {
            return localVarFp.customersSetupCiscoPost(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * Customer summary account
         * @summary Customer summary account
         * @param {CustomersApiCustomersSummaryPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSummaryPost(requestParameters: CustomersApiCustomersSummaryPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerSummaryResponse> {
            return localVarFp.customersSummaryPost(requestParameters.request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for customersCertificatePost operation in CustomersApi.
 * @export
 * @interface CustomersApiCustomersCertificatePostRequest
 */
export interface CustomersApiCustomersCertificatePostRequest {
    /**
     * customer username and password (same ocserv account).
     * @type {CustomerSummaryData}
     * @memberof CustomersApiCustomersCertificatePost
     */
    readonly request: CustomerSummaryData
}

/**
 * Request parameters for customersDisconnectSessionsPost operation in CustomersApi.
 * @export
 * @interface CustomersApiCustomersDisconnectSessionsPostRequest
 */
export interface CustomersApiCustomersDisconnectSessionsPostRequest {
    /**
     * customer username and password (same ocserv account).
     * @type {CustomerSummaryData}
     * @memberof CustomersApiCustomersDisconnectSessionsPost
     */
    readonly request: CustomerSummaryData
}

/**
 * Request parameters for customersSetupCiscoCertificateTokenGet operation in CustomersApi.
 * @export
 * @interface CustomersApiCustomersSetupCiscoCertificateTokenGetRequest
 */
export interface CustomersApiCustomersSetupCiscoCertificateTokenGetRequest {
    /**
     * Cisco Secure Client setup certificate token
     * @type {string}
     * @memberof CustomersApiCustomersSetupCiscoCertificateTokenGet
     */
    readonly token: string
}

/**
 * Request parameters for customersSetupCiscoPost operation in CustomersApi.
 * @export
 * @interface CustomersApiCustomersSetupCiscoPostRequest
 */
export interface CustomersApiCustomersSetupCiscoPostRequest {
    /**
     * customer username and password (same ocserv account).
     * @type {CustomerSummaryData}
     * @memberof CustomersApiCustomersSetupCiscoPost
     */
    readonly request: CustomerSummaryData
}

/**
 * Request parameters for customersSummaryPost operation in CustomersApi.
 * @export
 * @interface CustomersApiCustomersSummaryPostRequest
 */
export interface CustomersApiCustomersSummaryPostRequest {
    /**
     * customer username and password (same ocserv account).
     * @type {CustomerSummaryData}
     * @memberof CustomersApiCustomersSummaryPost
     */
    readonly request: CustomerSummaryData
}

/**
 * CustomersApi - object-oriented interface
 * @export
 * @class CustomersApi
 * @extends {BaseAPI}
 */
export class CustomersApi extends BaseAPI {
    /**
     * Download customer\'s own .p12 certificate bundle using ocserv username/password
     * @summary Download customer certificate
     * @param {CustomersApiCustomersCertificatePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApi
     */
    public customersCertificatePost(requestParameters: CustomersApiCustomersCertificatePostRequest, options?: RawAxiosRequestConfig) {
        return CustomersApiFp(this.configuration).customersCertificatePost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * disconnects all online sessions for a customer
     * @summary Disconnect all online sessions of a customer
     * @param {CustomersApiCustomersDisconnectSessionsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApi
     */
    public customersDisconnectSessionsPost(requestParameters: CustomersApiCustomersDisconnectSessionsPostRequest, options?: RawAxiosRequestConfig) {
        return CustomersApiFp(this.configuration).customersDisconnectSessionsPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Download customer\'s PKCS#12 certificate using a short-lived Cisco Secure Client setup token
     * @summary Download customer Cisco Secure Client setup certificate
     * @param {CustomersApiCustomersSetupCiscoCertificateTokenGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApi
     */
    public customersSetupCiscoCertificateTokenGet(requestParameters: CustomersApiCustomersSetupCiscoCertificateTokenGetRequest, options?: RawAxiosRequestConfig) {
        return CustomersApiFp(this.configuration).customersSetupCiscoCertificateTokenGet(requestParameters.token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create Cisco Secure Client certificate import and connection creation URIs using ocserv username/password
     * @summary Create customer Cisco Secure Client setup links
     * @param {CustomersApiCustomersSetupCiscoPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApi
     */
    public customersSetupCiscoPost(requestParameters: CustomersApiCustomersSetupCiscoPostRequest, options?: RawAxiosRequestConfig) {
        return CustomersApiFp(this.configuration).customersSetupCiscoPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Customer summary account
     * @summary Customer summary account
     * @param {CustomersApiCustomersSummaryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApi
     */
    public customersSummaryPost(requestParameters: CustomersApiCustomersSummaryPostRequest, options?: RawAxiosRequestConfig) {
        return CustomersApiFp(this.configuration).customersSummaryPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }
}

