/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
// @ts-ignore
import type { SystemResetAdminPassword } from '../models';
// @ts-ignore
import type { SystemResetPasswordResponse } from '../models';
/**
 * SystemUserApi - axios parameter creator
 * @export
 */
export const SystemUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Reset admin password by secret key
         * @summary Reset admin password by secret key
         * @param {SystemResetAdminPassword} request Reset admin password data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemUserResetPasswordPost: async (request: SystemResetAdminPassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('systemUserResetPasswordPost', 'request', request)
            const localVarPath = `/system/user/reset-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemUserApi - functional programming interface
 * @export
 */
export const SystemUserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemUserApiAxiosParamCreator(configuration)
    return {
        /**
         * Reset admin password by secret key
         * @summary Reset admin password by secret key
         * @param {SystemResetAdminPassword} request Reset admin password data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemUserResetPasswordPost(request: SystemResetAdminPassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemResetPasswordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemUserResetPasswordPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemUserApi.systemUserResetPasswordPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemUserApi - factory interface
 * @export
 */
export const SystemUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemUserApiFp(configuration)
    return {
        /**
         * Reset admin password by secret key
         * @summary Reset admin password by secret key
         * @param {SystemUserApiSystemUserResetPasswordPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemUserResetPasswordPost(requestParameters: SystemUserApiSystemUserResetPasswordPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SystemResetPasswordResponse> {
            return localVarFp.systemUserResetPasswordPost(requestParameters.request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for systemUserResetPasswordPost operation in SystemUserApi.
 * @export
 * @interface SystemUserApiSystemUserResetPasswordPostRequest
 */
export interface SystemUserApiSystemUserResetPasswordPostRequest {
    /**
     * Reset admin password data
     * @type {SystemResetAdminPassword}
     * @memberof SystemUserApiSystemUserResetPasswordPost
     */
    readonly request: SystemResetAdminPassword
}

/**
 * SystemUserApi - object-oriented interface
 * @export
 * @class SystemUserApi
 * @extends {BaseAPI}
 */
export class SystemUserApi extends BaseAPI {
    /**
     * Reset admin password by secret key
     * @summary Reset admin password by secret key
     * @param {SystemUserApiSystemUserResetPasswordPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemUserApi
     */
    public systemUserResetPasswordPost(requestParameters: SystemUserApiSystemUserResetPasswordPostRequest, options?: RawAxiosRequestConfig) {
        return SystemUserApiFp(this.configuration).systemUserResetPasswordPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }
}

