/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerModelCustomer
 */
export interface CustomerModelCustomer {
    /**
     * 
     * @type {boolean}
     * @memberof CustomerModelCustomer
     */
    'certificate_available': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerModelCustomer
     */
    'certificate_enabled': boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerModelCustomer
     */
    'deactivated_at': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerModelCustomer
     */
    'expire_at': string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerModelCustomer
     */
    'is_locked': boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerModelCustomer
     */
    'owner': string;
    /**
     * Receive in bytes
     * @type {number}
     * @memberof CustomerModelCustomer
     */
    'rx': number;
    /**
     * in GiB  >> x * 1024 ** 3
     * @type {number}
     * @memberof CustomerModelCustomer
     */
    'traffic_size': number;
    /**
     * 
     * @type {string}
     * @memberof CustomerModelCustomer
     */
    'traffic_type': CustomerModelCustomerTrafficTypeEnum;
    /**
     * Transmit in bytes
     * @type {number}
     * @memberof CustomerModelCustomer
     */
    'tx': number;
    /**
     * 
     * @type {string}
     * @memberof CustomerModelCustomer
     */
    'username': string;
}

export const CustomerModelCustomerTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    MONTHLY_RX_TX: 'MonthlyRxTx',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive',
    TOTALLY_RX_TX: 'TotallyRxTx'
} as const;

export type CustomerModelCustomerTrafficTypeEnum = typeof CustomerModelCustomerTrafficTypeEnum[keyof typeof CustomerModelCustomerTrafficTypeEnum];


