/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerIOSSetupResponse
 */
export interface CustomerIOSSetupResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomerIOSSetupResponse
     */
    'certificate_import_uri': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerIOSSetupResponse
     */
    'certificate_password': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerIOSSetupResponse
     */
    'connection_create_uri': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerIOSSetupResponse
     */
    'connection_name': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerIOSSetupResponse
     */
    'expires_at': string;
    /**
     * 
     * @type {string}
     * @memberof CustomerIOSSetupResponse
     */
    'server_address': string;
    /**
     * 
     * @type {number}
     * @memberof CustomerIOSSetupResponse
     */
    'server_port': number;
}

