/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HomeTelegramServiceStatus
 */
export interface HomeTelegramServiceStatus {
    /**
     * 
     * @type {string}
     * @memberof HomeTelegramServiceStatus
     */
    'bot_username'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HomeTelegramServiceStatus
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HomeTelegramServiceStatus
     */
    'has_bot_token'?: boolean;
}

