/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsOcservUserCertificateBackup
 */
export interface ModelsOcservUserCertificateBackup {
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserCertificateBackup
     */
    'cert_pem'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserCertificateBackup
     */
    'key_pem'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserCertificateBackup
     */
    'p12_base64'?: string;
    /**
     * active or suspended
     * @type {string}
     * @memberof ModelsOcservUserCertificateBackup
     */
    'status'?: string;
}

