/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsUserSession
 */
export interface ModelsUserSession {
    /**
     * 
     * @type {string}
     * @memberof ModelsUserSession
     */
    'Device': string;
    /**
     * 
     * @type {object}
     * @memberof ModelsUserSession
     */
    'ID': object;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserSession
     */
    'IPv4': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserSession
     */
    'Session started at': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserSession
     */
    'Username': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserSession
     */
    'vhost': string;
}

