/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservUserCertificateBackup } from './models-ocserv-user-certificate-backup';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservUserConfig } from './models-ocserv-user-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOnlineUserSession } from './models-online-user-session';

/**
 * 
 * @export
 * @interface ModelsOcservUser
 */
export interface ModelsOcservUser {
    /**
     * 
     * @type {ModelsOcservUserCertificateBackup}
     * @memberof ModelsOcservUser
     */
    'certificate'?: ModelsOcservUserCertificateBackup;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUser
     */
    'certificate_available'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUser
     */
    'certificate_enabled'?: boolean;
    /**
     * 
     * @type {ModelsOcservUserConfig}
     * @memberof ModelsOcservUser
     */
    'config'?: ModelsOcservUserConfig;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'deactivated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'group': string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUser
     */
    'is_locked': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUser
     */
    'is_online': boolean;
    /**
     * 
     * @type {Array<ModelsOnlineUserSession>}
     * @memberof ModelsOcservUser
     */
    'online_sessions': Array<ModelsOnlineUserSession>;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'owner': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'password': string;
    /**
     * Receive in bytes
     * @type {number}
     * @memberof ModelsOcservUser
     */
    'rx': number;
    /**
     * in GiB  >> x * 1024 ** 3
     * @type {number}
     * @memberof ModelsOcservUser
     */
    'traffic_size': number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'traffic_type': ModelsOcservUserTrafficTypeEnum;
    /**
     * Transmit in bytes
     * @type {number}
     * @memberof ModelsOcservUser
     */
    'tx': number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUser
     */
    'username': string;
}

export const ModelsOcservUserTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    MONTHLY_RX_TX: 'MonthlyRxTx',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive',
    TOTALLY_RX_TX: 'TotallyRxTx'
} as const;

export type ModelsOcservUserTrafficTypeEnum = typeof ModelsOcservUserTrafficTypeEnum[keyof typeof ModelsOcservUserTrafficTypeEnum];


