/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemPatchSystemUpdateData
 */
export interface SystemPatchSystemUpdateData {
    /**
     * 
     * @type {boolean}
     * @memberof SystemPatchSystemUpdateData
     */
    'auto_delete_inactive_users': boolean;
    /**
     * 
     * @type {string}
     * @memberof SystemPatchSystemUpdateData
     */
    'client_profile_connection_name': string;
    /**
     * 
     * @type {string}
     * @memberof SystemPatchSystemUpdateData
     */
    'client_profile_server_address': string;
    /**
     * 
     * @type {number}
     * @memberof SystemPatchSystemUpdateData
     */
    'client_profile_server_port': number;
    /**
     * 
     * @type {string}
     * @memberof SystemPatchSystemUpdateData
     */
    'google_captcha_secret_key': string;
    /**
     * 
     * @type {string}
     * @memberof SystemPatchSystemUpdateData
     */
    'google_captcha_site_key': string;
    /**
     * 
     * @type {number}
     * @memberof SystemPatchSystemUpdateData
     */
    'keep_inactive_user_days': number;
}

